### ISSUE TITLE
fix task set hostname

### ISSUE THREAD

**Issue by janitor-of-code** [fw-oss/ansible-role-default-setup#3]
file: tasks/main.yml line: 30-34  
```yaml
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
    use: systemd
  notify: Reboot
```

This didn't work in our pipeline. might've something to do with the `use` keyword. Removing it made it work on Ubuntu at least  
I've commented this task for now to be able to continue with a working pipeline
